# Site settings
name: 大道至简
email: kwyang@thoughtworks.com
author: Kevin Yang
# url: http://www.hifreud.com
# resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/tttyyhywb
baseurl: ""
description: 
meta_description: 
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: tttyyhywb



